version: "3.8"

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: bankappdb
      MYSQL_ROOT_PASSWORD: Test@123
    networks:
      - bankapp

  bankapp:
    build: .
    container_name: bankapp
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - "8080:8080"
    networks:
      - bankapp

networks:
  bankapp: